background_opacity 0.8
background_blur 1

# BEGIN_KITTY_THEME
# The Hulk
include current-theme.conf
# END_KITTY_THEME


# Перейти к следующей вкладке
map alt+right    next_tab
# Перейти к предыдущей вкладке
map alt+left     previous_tab

map ctrl+n new_tab
map ctrl+d close_tab


# Перемещение по словам
map ctrl+shift+left send_text all \x1b\x62
map ctrl+shift+right send_text all \x1b\x66

# Удаление слова (эмуляция Ctrl+Backspace)
map ctrl+backspace send_text all \x17

# выделение последнего вывода команды
map ctrl+shift+e run_kitten hints --type=regex --program=@не


cursor_shape beam

cursor_trail 2
confirm_os_window_close 0


